### ISSUE TITLE
Exception when trying to present white hair to rarity

### ISSUE THREAD

**Issue by MatthieuMB** [Steveice10/MyLittleInvestigations-Java#6]
Presenting white hair just after being combined with opal to rarity throw an exception and freeze the game. (On debian Gnu/Linux using the Desktop build from github)

```
 Exception in thread "LWJGL Application" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at org.spacehq.mylittleinvestigationsjava.Events.EvidenceSelectorEventProvider.RaiseEvidencePresented(EvidenceSelectorEventProvider.java:21)
	at org.spacehq.mylittleinvestigationsjava.UserInterface.EvidenceSelector.OnEvidencePresented(EvidenceSelector.java:551)
	at org.spacehq.mylittleinvestigationsjava.UserInterface.EvidenceSelector.Update(EvidenceSelector.java:288)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Encounter.Update(Encounter.java:253)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Location.Update(Location.java:468)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Area.Update(Area.java:71)
	at org.spacehq.mylittleinvestigationsjava.CaseInformation.Case.Update(Case.java:412)
	at org.spacehq.mylittleinvestigationsjava.Screens.GameScreen.Update(GameScreen.java:157)
	at org.spacehq.mylittleinvestigationsjava.Game.update(Game.java:287)
	at org.spacehq.mylittleinvestigationsjava.Game.render(Game.java:252)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:206)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.buffersProcessed(ChannelLWJGLOpenAL.java:493)
	at paulscode.sound.Source.stream(Source.java:570)
	at paulscode.sound.StreamThread.run(StreamThread.java:111)
```

**Comment by Steveice10** [comment]
Should be fixed now.

**Comment by MatthieuMB** [comment]
Fixed as well.
