### ISSUE TITLE
Exception when talking to sweetie belle

### ISSUE THREAD

**Issue by MatthieuMB** [Steveice10/MyLittleInvestigations-Java#7]
After presenting the star to sweetie belle, she go away to bring the ribbon and the the game freeze with this exception. This part is important to finish the game.

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Conversation$CharacterChangeAction.Begin(Conversation.java:656)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Conversation$MultipleCharacterChangeAction.Begin(Conversation.java:580)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Conversation.Update(Conversation.java:235)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Encounter.Update(Encounter.java:290)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Location.Update(Location.java:468)
	at org.spacehq.mylittleinvestigationsjava.CaseContent.Area.Update(Area.java:71)
	at org.spacehq.mylittleinvestigationsjava.CaseInformation.Case.Update(Case.java:412)
	at org.spacehq.mylittleinvestigationsjava.Screens.GameScreen.Update(GameScreen.java:157)
	at org.spacehq.mylittleinvestigationsjava.Game.update(Game.java:287)
	at org.spacehq.mylittleinvestigationsjava.Game.render(Game.java:252)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:206)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.buffersProcessed(ChannelLWJGLOpenAL.java:493)
	at paulscode.sound.Source.stream(Source.java:570)
	at paulscode.sound.StreamThread.run(StreamThread.java:111)
```

**Comment by Steveice10** [comment]
Can you try re-downloading the game and seeing if it works? Might be fixed now.

**Comment by MatthieuMB** [comment]
Fixed, thank you very much. I'm still playing it. I will report if I see anything else.
